### ISSUE TITLE
How does one check whether a Client object is valid?

### ISSUE THREAD

**Issue by winbatch** [adobe-research/libkafka#3]
Let's say I have the wrong broker host/port (or it's not up).  In the sample producer code, it has a Client object.  Doesn't look like the Client object has an isValid() or equivalent?

Connect::open():getaddrinfo error:Name or service not known
Client::prepareConnection():connection->open() failed
Segmentation fault

**Comment by DavidTompkins** [comment]
The Client object is a collection of metadata needed to connect to a broker. The Connection is opened only after you call any of the Client::send*Request() functions (e.g. Client::sendProduceRequest()), and the return value of those functions will be NULL if any errors occur while opening the connection, transferring the request, receiving the response, or closing the connection. If the return value is NULL, you can inspect errno to get the system error ID. There is no isValid() or equivalent, given these semantics.

But you bring up a good point -- the sample code should be checking for the NULL return value, and it is not (hence the seg fault). I'll fix that.

Thanks.

**Comment by winbatch** [comment]
Unrelated questions:
- how can I get error strings, etc so that I can write them to my own logs?
- do you have a sample of writing to partitions? (Keys, etc)
- do you have a sample of writing to a cluster instead of a single broker?
